Homework2
made-ml-in-prod-2022/akurilovich pull request #2
Opened 2022-05-29 20:52 UTC by Lemm1ng

Pull request. Самооценка по HW02.

С докером попытаюсь разобраться чуть позже (не выйдет до окончания мягкого дедлайна). Споткнулся об разворачивание docker desktop из под windows 10. Какая-то магия, все падает, все рушится. Придется срочно мигрировать в Ubuntu. Было бы интересно узнать Ваш опыт работы с Docker из под винды.

Основная часть

- [x] **3 балла** Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict (3 балла)

- [x] **1 балл**  Напишите endpoint /health (1 балл), должен возращать 200, если ваша модель готова к работе (такой чек особенно актуален если делаете доп задание про скачивание из хранилища)

- [x] **3 балла** Напишите unit тест для /predict (3 балла) (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/)

- [x] **2 балл** Напишите скрипт, который будет делать запросы к вашему сервису -- 2 балла

- [] **0 баллов** Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run), внутри контейнера должен запускать сервис, написанный в предущем пункте, закоммитьте его, напишите в readme корректную команду сборки (4 балл)

- [] **0 баллов**опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (+2 балла)

- [] **0 баллов** напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл) Убедитесь, что вы можете протыкать его скриптом из пункта 3

- [x] **1 балл** проведите самооценку(распишите в реквесте какие пункты выполнили и на сколько баллов, укажите сумму баллов) -- 1 балл

Дополнительная часть:

- [] **0 баллов** Ваш сервис скачивает модель из S3 или любого другого хранилища при старте, путь для скачивания передается через переменные окружения (+2 доп балла)

- [] **0 баллов**  Оптимизируйте размер docker image (+2 доп балла) (опишите в readme.md что вы предприняли для сокращения размера и каких результатов удалось добиться -- должно получиться мини исследование, я сделал тото и получился такой-то результат) https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

- [x] **2 баллa** Сделайте валидацию входных данных https://pydantic-docs.helpmanual.io/usage/validators/ (например, порядок колонок не совпадает с трейном, типы, допустимые максимальные и минимальные значения, проявите фантазию, это доп. баллы, проверка не должна быть тривиальной) (вы можете сохранить вместе с моделью доп информацию, о структуре входных данных, если это нужно) -- 2 доп балла https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена

2022-06-19 16:59 UTC, SVizor42 commented on homework2/tests/test_online_inference_app.py
> +from ..online_inference.online_inference_api import app, start_app
Стандартные импорты идут до локальных

2022-06-19 17:00 UTC, SVizor42 commented on homework2/tests/test_online_inference_app.py
> +start_app(PATH_TO_DEFAULT_MODEL)
А это отработает, если передать туда аргумент?

2022-06-19 17:01 UTC, SVizor42 commented on homework2/online_inference/online_inference_api.py
> +from requests.exceptions import MissingSchema
Этот импорт используется?

2022-06-19 17:03 UTC, SVizor42 commented on homework2/online_inference/request_to_api.py
> +@click.argument("prediction-save-path")
Предлагаю также задать значения по дефолту, чтобы каждый раз не передавать аргументы

2022-06-19 17:11 UTC, SVizor42 commented on homework2/README.md
> +На текущий момент для десериализации модели требуется пакет ml_project из homework1. Сначала нужно установить его.
В рамках ДЗ можно было скопировать часть кода. Можно оставить и так, но скорее всего это приведет к утяжелению образа

2022-06-19 17:11 UTC, SVizor42 requested changes
Комментарии:

1. Нужно убрать лишние папки (`pytets_cache` и т.д.)
2. Не получилось найти доп. пункт по валидации входных данных
3. Предлагаю дополнить тесты вариантами с некорректными входными данными (сервис должен вернуть статус 4xx)

2022-06-21 10:15 UTC, Lemm1ng commented on homework2/tests/test_online_inference_app.py
> +from ..online_inference.online_inference_api import app, start_app
Разделил ипортирование сторонних библиотек и локальных модулей

2022-06-21 10:28 UTC, Lemm1ng commented on homework2/tests/test_online_inference_app.py
> +start_app(PATH_TO_DEFAULT_MODEL)
Странно что работало, исправил.

2022-06-21 10:31 UTC, Lemm1ng commented on homework2/online_inference/online_inference_api.py
> +from requests.exceptions import MissingSchema
нет, не используется, удалил.

2022-06-21 10:35 UTC, Lemm1ng commented on homework2/online_inference/request_to_api.py
> +@click.argument("prediction-save-path")
Если можно, я бы оставил как есть. Логика была что если мы скачиваем и используем скрипт для запросов к api на своей машине, то мы должны сами явно задавать где у нас лежат данные, к какому серверу обращаемся и  куда пишем предсказания. Соответсвенно нет турудно интерпретируемого поведения скрипта.

2022-06-21 11:23 UTC, Lemm1ng commented on homework2/README.md
> +На текущий момент для десериализации модели требуется пакет ml_project из homework1. Сначала нужно установить его.
В идеале, следовало бы залить проект из HW01 на PyPi и устанавливать через pip :) В учебной задаче нецелесообразно. В hw01 использовал кастомный class DatasetTransformer, пришлось бы много копипастить. Образ конечно утяжелится, но будет проще понимать что происходит.

2022-06-21 12:01 UTC, Lemm1ng commented
1. Лишние файлы убраны.
2. Валидация входных файлов. сlass HeartDataSubmission(BaseModel) из online_inference_api.py отвечает за валидацию входных данных.
3. Добавлен тест с некорректными входными данными (см пред пункт.) Проверяется возврат статуса 422 Unprocessable Entity.

2022-06-21 12:01 UTC, merged

2022-06-21 21:06 UTC, SVizor42 reviewed
1. Сам класс не гарантирует валидацию данных. Проверку можно реализовать при помощи [pydantic](https://pydantic-docs.helpmanual.io/usage/validators/) или использовать свою кастомную реализацию. Этот доп. пункт не могу зачесть.
2. На будущее - мерджить ветку нужно после того, как будут выставлены баллы и получен аппрув.

**Сумма: 21 балл**